name: Build Custom

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  macos-build:
    runs-on: mary_runner
    name: 🍎 macOS 11.0 (ARM64)
    steps:

    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: ⬇️ Install dependencies
      run: |
        arch -arm64 brew bundle --no-lock --file dist/Brewfile

    - name: ✋ Build
      run: |
        mkdir build
        cd build
        CC=$(brew --prefix llvm)/bin/clang \
        CXX=$(brew --prefix llvm)/bin/clang++ \
        PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix)/lib/pkgconfig" \
        arch -arm64 cmake \
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCREATE_BUNDLE=ON \
          -DCREATE_PACKAGE=ON \
          ..
        arch -arm64 make -j 4 package

    - name: 📦 Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: macOS DMG
        path: build/*.dmg
